### ISSUE TITLE
webpack.ResolverPlugin not present?

### ISSUE THREAD

**Issue by riemers** [preboot/angular-webpack#10]
Forgive me if i am placing it in the wrong spot, but pretty new here for me. I had your old version working and i used the resolverplugin to get bower compontents in. With the new version it doesn't work anymore if i add:
````
config.plugins = [
      new webpack.ResolverPlugin([
          new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin("bower.json", ["main"])
      ], ["normal", "loader"])
];
````
I get:
    Error: Cannot find module './ResolverPlugin'

I did a fresh install/clean etc, checked that the name is present in webpack.js, which it is. What am i doing wrong? Or is it the webpack 2 issue?

**Comment by Foxandxss** [comment]
I am gonna revert webpack 2 today, so you can check again.

**Comment by riemers** [comment]
It worked on the older version though, just not on the webpack 2 beta.

**Comment by Foxandxss** [comment]
Don't worry, you will be able to get all the new features I introduced as soon as I revert webpack, just webpack, the features will be there.

**Comment by riemers** [comment]
:+1:

**Comment by Foxandxss** [comment]
I reverted webpack version, this should work now with the latest version.
