### ISSUE TITLE
karma "TDD Style"

### ISSUE THREAD

**Issue by ollwenjones** [preboot/angular-webpack#114]
I tried to run this on TDD style `npm` script, and 
- Problem 1: it with all my various test errors, it ran once and then hung. 
- Problem 2: If I stopped the task (ctrl+c) and ran it again, it had to find the next available port each time, so these instances were stacking up

FWIW: I was running in `git bash` on Windows 10.

**Comment by Foxandxss** [comment]
That is weeird. Sadly I don't have any Windows box to debug.

**Comment by ollwenjones** [comment]
Was hoping some other windows user would come on and say, "All you have to do us _____." I guess I'll have to try to debug it when I get the chance.

**Comment by ollwenjones** [comment]
It's right after the console output of the coverage report that it hangs, so I wonder if that's where the issue is... In a way, I'm not as concerned about coverage while I'm writing the unit test - at each iteration, I minimally need it to run the test of the file I'm saving, or the test-file that I'm saving. The whole-shebang with coverage report,etc. I, for one, would be okay with running once at a time.

**Comment by Foxandxss** [comment]
You can remove the coverage reporter at karma.

**Comment by ollwenjones** [comment]
I added a `karma.tdd.conf.js` to my project, without either coverage report task, and it worked just fine as a watch / TDD task. I'm not sure that really solves the issue I was having, but it was a good workaround for getting things done.

**Comment by Foxandxss** [comment]
We iterated a lot since here Sam. Is this still an issue? If so, open a new issue and we fix it.
