### ISSUE TITLE
HMR and differents

### ISSUE THREAD

**Issue by AndersonDev** [preboot/angular-webpack#118]
Hi. Sory for posting supp question here.

1) It takes a bit time to reload page when I edit html or css. May I add some stuff to do it quickly? Some Hot Module Replacement?
2) Here some + or - to use this kit [https://github.com/AngularClass/angular2-webpack-starter](url)?

Thanks!

**Comment by Foxandxss** [comment]
I was waiting for it to be more stable, so I will check soon.

**Comment by AndersonDev** [comment]
@Foxandxss ok. I am using this kit because it is wery simple and work fine)

I have an erorr after some update from repisitory:
![image](https://cloud.githubusercontent.com/assets/6890368/16569485/a640141e-423f-11e6-8461-e0e1f0693202.png)

Cant find reason(

**Comment by Foxandxss** [comment]
I never put support for scss component styles.

I need to consider that.

**Comment by AndersonDev** [comment]
@Foxandxss What? I don't understend you) All was ok 2 days ago, I chang something and have this error

**Comment by Foxandxss** [comment]
Really? that is weird. I force a raw loader for that files.

**Comment by AndersonDev** [comment]
@Foxandxss realy?
```
 {
        test: /\.scss$/,
        exclude: root('src', 'app'),
        loader: isTest ? 'null' : ExtractTextPlugin.extract('style', 'css?sourceMap!postcss!sass')
      },
      // all css required in src/app files will be merged in js files
      {test: /\.scss$/, exclude: root('src', 'style'), loader: 'raw!postcss!sass'},
```

**Comment by Foxandxss** [comment]
Yes, really. That confirms it.

**Comment by AndersonDev** [comment]
@Foxandxss sory me... I downloaded this kit one month ago. Start developing. All was fine up to today. What I am doing wrong? Where is my error? Thanks!

**Comment by Foxandxss** [comment]
Oh lies, it is supposed to work. I don't know what happened. I will need to research it myself when I have a minute.

**Comment by AndersonDev** [comment]
@Foxandxss Ahhh... Trouble I think with angular2-template-loader. I have requires.

**Comment by Foxandxss** [comment]
that loader work with old and new syntax. Or it should :)

**Comment by AndersonDev** [comment]
@Foxandxss It **should** hovewer it **not**. I replased all components to new syntax and all works! Sory and thanks)

**Comment by Foxandxss** [comment]
I will leave this open to not forget to test it.
