### ISSUE TITLE
Not as much an issue, but a question for improvement

### ISSUE THREAD

**Issue by riemers** [preboot/angular-webpack#12]
I know you added the copy web plugin, so you can copy assets from your src to build. Isn't there something that can parse the html that sees images and then hashes it, as it does right now with all my css that is being loaded and all other things it 'requires'. Because i have like a banner at the top in the html in my code. So i have all these fancy hashes of everything, except for that banner file which is just copied over. I tried to look around, but i could only find a possible solution by using includes or using an extra file which defeats the purpose of the automation. Any thoughts?

**Comment by Foxandxss** [comment]
Yeah, I discovered that instead of using the raw loader to treat the html templates, there is a html-loader that does exactly what you ask.

I am investigating all of this to be 100% sure that I can get rid of copying the assets.

When I verify this, I Will update both starters to do this.

**Comment by riemers** [comment]
I went back to the webpack 1.0 and it is working like a charm so far. I am also using bower, but i am loading that in via:

````
  config.resolve = {
    modulesDirectories: ["bower_components","node_modules"]
  };
````
and
````

        new webpack.ResolverPlugin([
          new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin("bower.json", ["main"])
        ], ["normal", "loader"]),
````
Under config.plugins.push.

That way i can say as example "import bootstrap from 'bootstrap'" if there is a bower component called bootstrap with that name advertised in bower.json.

Might be helpfull for others, or as comment/example unless you have a better way.

I'll use the image for now until you have an update for that part, its not a showstopper :+1:

**Comment by Foxandxss** [comment]
Is there any good reason to use bower? Bower is pretty dead.

**Comment by riemers** [comment]
I work in a office where "innovation" is guarded by paperwork. So they have not yet moved from bower type repo's to npm type repo's internally.

**Comment by riemers** [comment]
Btw, any thoughts about ng-annotate-webpack-plugin? Or is your idea 'write it correct for minimize'?

**Comment by Foxandxss** [comment]
The problem with this automatic tools is that it doesn't work 100%, so if you rely on "It will work", it could left one injection without min safe and good luck with your "I can't inject `e`" and find where.

On the other hand, even when using `$inject` by hand is more tedious, seems like the community is shifting into doing that vs automatic tools.

**Comment by riemers** [comment]
That's the idea i was getting too, since i didn't had that yet and used it in the past. Better to write the code complete then. Also, you need any help on the html-loader, or anything i can do to assist?

**Comment by Foxandxss** [comment]
Don't worry, I need to figure out some other things on the ng2 repo first and implement it there so I can come back here with those ideas. I have been a bit AFK the past few days.

**Comment by riemers** [comment]
Also, purifycss and any other form of reducing the size of the output would be nice. Bootstrap with a simple app has a lot of overhead. (as example) got a couple of css files which has tons of stuff in it that i don't use. Or am i missing something.

**Comment by riemers** [comment]
If you point me in the right direction i can look into this, also i've noticed that i am not using chunks accordingly. An example where the app and the vendor would be seperated in chunks for example would be a nice addition perhaps.

**Comment by Foxandxss** [comment]
you just need to use the html-loader instead of raw-loader, that pretty much does it. It had some issues with angular and I had to research it.

About splitting into app and vendor, in the ng2 version of this starter you can see that.

**Comment by riemers** [comment]
Ok, in that case i'll close this ticket then 👍

**Comment by thematan** [comment]
i think it can be of much help to state that there is no use of ng-annotate in the readme

**Comment by Foxandxss** [comment]
Sorry but I don't agree. If I need to state every tool I don't use, that would use a lot of space.

You can add it to your project if you want tho :)
