### ISSUE TITLE
Foundation 6 / Bootstrap 4 - Correct way to use sass setting file

### ISSUE THREAD

**Issue by frankspin89** [preboot/angular-webpack#126]
Foundation 6 comes with a global settings.scss file to customize the look and feel. I was wondering what is the correct way to load this in to my project. 

I installed foundation-sites via NPM and added the following line to my vendor.ts

`import 'foundation-sites';`

In src/style i have the following two files
- app.scss
- _settings.scss 

In app.scss i have the following code

```
@import 'settings';
@import '~foundation-sites/scss/foundation';

body {
    background: $primary-color;
}
```

This is working great. When i change the $primary-color var in settings.scss i see the desired result. So far, so good.

Now i want to add a button style to my app.component. So in app.component.scss i first did the following.

```
button {
  @include button;
}
```

That wasn't working, missing button mixin. So i added the reference to foundation to the file.

```
@import '~foundation-sites/scss/foundation';

button {
  @include button;
} 
```

This works, only it is rendering the default button style from foundation and it don't respect the override i made in settings.scss. So i added the reference to settings file:

```
@import '~src/style/settings';
@import '~foundation-sites/scss/foundation';

button {
  @include button;
}
```

And it's working again. It just feels a bit cumbersome to make these two imports on each component. Is there a better way to do this?

**Comment by Foxandxss** [comment]
Sadly I don't have an answer to this because I don't really use SASS. That being said, I also would like to know the answer to this :/

**Comment by mattdistefano** [comment]
AFAIK you have to have to all the `@imports` in each file, since really you're compiling a bunch of separate sass files, each with its own variables (vs. compiling partials where they all have access to the same variables).

In theory you could probably write a (pre?) loader that adds the relevant `@import` before handing off to the sass-loader.

We're still investigating this issue ourselves but ATM are just sticking with a single app-level stylesheet.

**Comment by Foxandxss** [comment]
I would like to give a solution similar to the CLI To this global styles. We will see.
