### ISSUE TITLE
[CSS] SyntaxError: Unexpected character '?' 

### ISSUE THREAD

**Issue by Websitescity** [preboot/angular-webpack#137]
Hello,
When I tried to include font-awesome in vender.ts I got an error that "@" is not recognised.
SyntaxError: Unexpected character '�' 

To fix it in webpack.config.js I replaced:

`{test: /\.(png|jpe?g|gif|svg|woff|woff2|ttf|eot|ico)$/, loader: 'file?name=fonts/[name].[hash].[ext]?'},`

with

`{test: /\.(png|jpe?g|gif|svg|woff|woff2|ttf|eot|ico)(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: 'file?name=fonts/[name].[hash].[ext]?'},`

Now I can just install font-awesome with:
`npm install font-awesome`

and include in vendor.ts
`import 'font-awesome/css/font-awesome.css';`

**Comment by Foxandxss** [comment]
Thanks for the detailed issue. I will try what you did and your solution.

**Comment by Foxandxss** [comment]
I think I did this long ago.
