### ISSUE TITLE
Typescript compiler errors

### ISSUE THREAD

**Issue by cmelion** [preboot/angular-webpack#14]
I was doing some refactoring of this fantastic seed project and started noticing some errors in the typescript compiler console.  I reverted but the errors were still there.  Is anyone else seeing this?

![Image of Typescript Compile Errors](https://raw.githubusercontent.com/cmelion/images/master/angular2-webpack/typescript-compiler-error.png)

**Comment by Foxandxss** [comment]
Wrong repo :P

Did you remove the "ignoreDiagnostic" bits?

**Comment by cmelion** [comment]
@Foxandxss I did not remove the ignoreDiagnostic bits, should I?

"Wrong repo"?  Sorry, is there a right repo :P

I just started migrating to Angular-2/TS from Angular 1.x and React/ES6 in the last few days, so there are some things I'm still acclimating to.

**Comment by Foxandxss** [comment]
Oh, I think I see your error, you are using webstorm's integrated compiled and you definitely shouldn't. That won't use webpack nor our ts-loader (that has the ignoreDiagnostic bits).

So what you have is not an error per se, it is just that you are using a different compiler that doesn't have all our options. I would disable the webstorm integrated compiler and just use our npm scripts.

Also yes, wrong repo, this is for Angular **1** :P, you are looking at the Angular 2 repo is a different one.

**Comment by cmelion** [comment]
damn!  I'm going blind ... sorry about that.
Thanks, for the quick reply.
