### ISSUE TITLE
Cannot run npm run watch, npm start will not watch for changes

### ISSUE THREAD

**Issue by DfKimera** [preboot/angular-webpack#15]
After running `npm start`, changing the entry JS file or the HTML file will not trigger a rebuild. Trying to run `npm run watch` will yield a `missing script: watch` error. Logs attached below.

When running `npm start` and updating `app.js` and `index.html`

```
➜  kyoto-web git:(master) ✗ npm start

> kyoto-web@1.0.0 start /Users/dfkimera/Projects/kyoto-web
> npm run server


> kyoto-web@1.0.0 server /Users/dfkimera/Projects/kyoto-web
> webpack-dev-server --history-api-fallback --inline --progress

 70% 1/1 build moduleshttp://localhost:8080/
webpack result is served from http://localhost:8080/
content is served from ./src/public
404s will fallback to /index.html
chunk    {0} app.bundle.js (app) 1.34 MB [rendered]
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 314 bytes [rendered]
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
chunk    {0} app.bundle.js (app) 1.34 MB
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 314 bytes
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
chunk    {0} app.bundle.js (app) 1.34 MB
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 341 bytes [rendered]
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
chunk    {0} app.bundle.js (app) 1.34 MB
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 360 bytes [rendered]
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
chunk    {0} app.bundle.js (app) 1.34 MB [rendered]
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 360 bytes
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
chunk    {0} app.bundle.js (app) 1.34 MB
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 631 bytes [rendered]
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
chunk    {0} app.bundle.js (app) 1.34 MB [rendered]
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 631 bytes
webpack: bundle is now VALID.
```

When running `npm run watch`
```
➜  kyoto-web git:(master) ✗ npm run watch
npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/Cellar/node/5.7.0/bin/node" "/usr/local/bin/npm" "run" "watch"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0

npm ERR! missing script: watch
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dfkimera/Projects/kyoto-web/npm-debug.log
```

**Comment by Foxandxss** [comment]
That log indicates me that it is re bundling the application with the changes, open localhost:8080 and check. I just tried with a fresh copy and it works fantastic.

About `npm run watch`. I don't have it on this repo (we do on the ng2 one). Will see what the advantages are to see if I implement it or not.

**Comment by JackForbes** [comment]
Just ran into the same thing, any updates on how you were able to get it working @DfKimera?

**Comment by DfKimera** [comment]
I didn't :/ I've spent a few good hours trying to get it working, to no avail. I ended up using Browserify instead.

**Comment by JackForbes** [comment]
Thanks for the quick response @DfKimera! @Foxandxss I noticed the following in the package.json of the ng2 one:
`"watch": "webpack --watch --progress --profile",`
Would this work here? Also, how do you recommend running this on prod, after doing a `npm run build`?

**Comment by Foxandxss** [comment]
Do you see anything good coming from that command? I never used it, but if there is value...

And yes, you can put your app in prod with that command.

**Comment by Foxandxss** [comment]
You don't want to run the slow webpack server on production.

What `npm run build` generate is your static application. Your best option is to serve that using nginx (or apache).

**Comment by JackForbes** [comment]
Oh ok gotcha, I didn't realize it wouldn't even have to run on localhost on the prod server. Thanks!
