### ISSUE TITLE
Deprecation warning on new install

### ISSUE THREAD

**Issue by anbiniyar** [preboot/angular-webpack#17]
```
npm WARN deprecated karma-phantomjs2-launcher@0.5.0: Use karma-phantomjs-launcher@1.0.0 instead
npm WARN deprecated phantomjs2-ext@0.2.2: Please use latest version of phantomjs
npm WARN deprecated npmconf@2.1.1: this package has been reintegrated into npm and is now out of date with respect to npm
```
Is there a reason why karma-phantomjs2 is being used? If not, I can try and upgrade it to the latest version and submit a pull request.

Where are my manners? Thank you for this repository. This is a great starting place!

**Comment by Foxandxss** [comment]
The phantomjs2 launcher was used there because the original one didn't support phantomjs 2 so that was a temporary workaround until the main one had support.

Seems like it works now so I changed it.

**Comment by anbiniyar** [comment]
That was quick! Thank you for doing this :)
