### ISSUE TITLE
Problem with image url in css

### ISSUE THREAD

**Issue by mbnsoft** [preboot/angular-webpack#171]
Image urls in scss/css doesn't work correctly.

**Comment by mbnsoft** [comment]
I found a solution, use [resolve-url-loader](https://www.npmjs.com/package/resolve-url-loader) plugin:

**For CSS files:**
```
{
    test: /\.css$/,
    exclude: root('src', 'app'),
    loader: isTest ? 'null' : ExtractTextPlugin.extract('style', 'css?resolve-url?sourceMap!postcss')
}
```
**For SCSS files:**
```
{
    test: /\.scss$/,
    exclude: root('src', 'app'),
    loader: isTest ? 'null' : ExtractTextPlugin.extract('style', 'css?resolve-url?sourceMap!postcss!sass')
}
```

**Comment by samfrach** [comment]
thank you, this solves my problem.

Thank you for integrating that change in the project.

**Comment by Foxandxss** [comment]
We could probably add this to the starter.

**Comment by hijoncon** [comment]
@mbnsoft how do you structure your image folder? Did you put it in the public?

**Comment by mbnsoft** [comment]
@hijoncon yes, sure!

**Comment by hijoncon** [comment]
@mbnsoft thanks :)

**Comment by gohilumesh** [comment]
Hi All,
I am trying to solve this but no success. Can we get this in please. 
Thanks Umesh

**Comment by Foxandxss** [comment]
Sorry I took to long to answer. What is the status of this?

**Comment by mbnsoft** [comment]
@Foxandxss It's solved in latest upgrades, Thanks!
