### ISSUE TITLE
build linking issue...

### ISSUE THREAD

**Issue by minstrelMan** [preboot/angular-webpack#18]
When I run the build process 'npm run build' all seems good...
...until I open/run the dist/index.html in a browser.  Nothing happens.

Perhaps there's a 'linking' issue within the build process?  No doubt a simple fix, but I'm just beginning this adventure.  

By the way, thanks for providing this workflow!

edit - I'm working with the current/original files; I've made not further adjustments.

**Comment by zombiQWERTY** [comment]
@minstrelMan, you must run your index.html from `./dist` by server. Put files in the root of the server or install `https://www.npmjs.com/package/http-server`. Then run server by this command: `http-server ./dist` and open in browser `localhost:8080`

**Comment by minstrelMan** [comment]
Thanks...sorted it out with solution found in issue/question #20.
