### ISSUE TITLE
Unreadable source code in unit tests

### ISSUE THREAD

**Issue by Bolza** [preboot/angular-webpack#181]
While running karma tests in Chrome if i open the source of any of my files i see the code full of this kind of tags:

`var __cov_BjOfkaBSXGboS9$AX48eiA  = [...]`

Basically the whole code is unreadable and impossible to debug, which is the whole point of running tests.

I tried disabling the coverage reporters (as i suppose that code is some kind of coverage marker) but nothing changes. 

Is there any change to the configuration i can try to solve this issue?

**Comment by Foxandxss** [comment]
I will investigate.

**Comment by Foxandxss** [comment]
Can you try with latest changes?
