### ISSUE TITLE
Too coupled with NPM (for karma at least)

### ISSUE THREAD

**Issue by OscarGalindo** [preboot/angular-webpack#194]
Since the webpack config is using **npm_lifecycle_event** it's impossible to run karma without the npm scripts.

I think it's better to have different webpack config files, one for each environment.

(I think this issue would help to someone to understand why can't run karma out of npm scripts and if you're agree i can try to do a PR)

**Comment by hijoncon** [comment]
I think they want this starter to be simple as much as possible. Check this https://github.com/preboot/angular2-webpack/pull/124

**Comment by Foxandxss** [comment]
I'll move to webpack 2 soon and fix that

**Comment by Foxandxss** [comment]
I moved, I didn't fix. I will fix it shortly tho in an experimental branch.
