### ISSUE TITLE
Relative path?

### ISSUE THREAD

**Issue by moneytree-doug** [preboot/angular-webpack#20]
I am deploying my dist to a subdirectory. I noticed the images assume from the root. I tried changing the publicPath, but now it doesn't work in local. I'm new to webpack, and I don't know what's the best way to do this.

**Comment by Foxandxss** [comment]
Check this PR from the ng2 version https://github.com/preboot/angular2-webpack/pull/63. Just one change in the webpack config and changing the forward slashes on the images.

Check if that works for you and if so, I will apply those changes here too.

**Comment by moneytree-doug** [comment]
@Foxandxss It didn't work. 

This is where it tries to fetch the resources from: 

```
GET https://example.jp/css/app.7fbb9ad57399e9d43470.css 
exa_mple.jp/:12 GET https://example.jp/scripts/app.7fbb9ad57399e9d43470.js 403 (Forbidden)
favicon.ico:1 GET https://example.jp/images/favicon.ico 403 (Forbidden)
```


This is where I expect it to fetch the resources from:
```
https://example.jp/subdirectory/css/app.7fbb9ad57399e9d43470.css 
https://example.jp/subdirectory/scripts/app.7fbb9ad57399e9d43470.js 
https://example.jp/subdirectory/images/favicon.ico 

```

**Comment by phra** [comment]
just declare a [base tag](http://www.w3schools.com/TAgs/tag_base.asp).

**Comment by techhysahil** [comment]
I have write solution for above problem as it occur to me too. Check http://blog.techhysahil.com/angular-2/deploy-angular-2-project-subdirectory/ for full detail.
