### ISSUE TITLE
directions for prod build

### ISSUE THREAD

**Issue by houston88** [preboot/angular-webpack#21]
Not exactly an issue, but as a webpack noob I could not see how to do prod build. Thanks!

**Comment by Foxandxss** [comment]
Uh, the docs is not that clear in that aspect. Thanks for the heads up.

You can generate prod build by running

```
$ npm run build
```

It will be in the `dist` folder.

**Comment by houston88** [comment]
Cool thanks. It blows up for me when I serve out the dist folder, looks like the module names are getting uglified. Hope to look into more this week. Any suggestions?
`angular.js:68Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:unpr] Unknown provider: t`
