### ISSUE TITLE
npm run build renders correct output, but hangs.

### ISSUE THREAD

**Issue by Hannesver** [preboot/angular-webpack#212]
When I do `npm run build`, it all runs well, until it gets to

```
Child extract-text-webpack-plugin:
        + 7 hidden modules
```

After that, it just doesn't do anything (I let it run for upwards to 2 hours).
I do get the correct files in my /dist folder though, but the CSS does not get minified.

**Comment by Foxandxss** [comment]
That is weird. That is actually the last step before it goes back to the prompt.

Perhaps your SCSS has something wrong and gets stuck, is the only thing that comes to my mind right now.

**Comment by Hannesver** [comment]
Hi

Thanks for the reply, must be something I did wrong, because I copied your version over again, and now it works. Anyway. I still do get an unminified css file. There are still a lot of newlines in there and indentation.

**Comment by mcescalante** [comment]
Try with the latest code and if you still have the same issue comment here or open a new issue, since lots has updated since this was opened 😄
