### ISSUE TITLE
no CSS sourcemap

### ISSUE THREAD

**Issue by Foxandxss** [preboot/angular-webpack#215]
Since I moved to webpack 2, I had to disable CSS sourcemap. I need to investigate how to get it back or report an error.

**Comment by atais** [comment]
+1 

I am using sass styles and in prod mode the source maps are available only for compiled css.
In test mode styles injected into head do not contain any sourcemap at all.

**Comment by Foxandxss** [comment]
Is that important to have CSS sourcemaps on testing? I never ever care about CSS on testing.

**Comment by atais** [comment]
Well, it is possible to find the source of certain style by looking for the effect it applies...
But, I guess, it is easier to simply click on it and directly get to the source file, isn't it?

**Comment by hbweb** [comment]
@atais - Adding @import scss file to app.scss does not seem to work for me.  I use sassLoaders in webpack.config.js to include the path. 

```
path.resolve(__dirname, "node_modules/bootstrap-sass/assets/stylesheets"),
```

Then, import bootstrap in app.scss file.

```
// Import Sass Dependencies
@import "bootstrap";        // Bootstrap v3.3.7

```

Any other suggestion? Cheers

**Comment by mcescalante** [comment]
I believe that on build, we are generating a CSS sourcemap again:

![screenshot](http://i.imgur.com/Rjxk5ow.png)

Going to close this 😄
