### ISSUE TITLE
i want to use bootstrap-loader but can't run app when i add new webpack.ProvidePlugin to the plugins array

### ISSUE THREAD

**Issue by joelmuskwe** [preboot/angular-webpack#218]
i want to use bootstrap-loader but can't run app when i add new webpack.ProvidePlugin to the plugins array.

Help required

**Comment by jbeckton** [comment]
what errors are you getting? can you post your code?

**Comment by mcescalante** [comment]
I am going to close this due to inactivity. If you are still having issues adding the webpack `ProvidePlugin` just comment here and I can help.
