### ISSUE TITLE
tests do not work

### ISSUE THREAD

**Issue by stevermeister** [preboot/angular-webpack#22]
I'm trying to run command

    node_modules/.bin/karma start

and getting such error
<img width="326" alt="screen shot 2016-04-28 at 11 07 02" src="https://cloud.githubusercontent.com/assets/1526680/14880833/5edbe33e-0d31-11e6-8bed-28ff2cae8714.png">

**Comment by Foxandxss** [comment]
Try with "npm test"

**Comment by stevermeister** [comment]
but it runs the same 
only with global karma 
https://github.com/preboot/angular-webpack/blob/master/package.json#L8
no?

**Comment by Foxandxss** [comment]
Yes, but sets a flag in webpack config that will enable / disable services for testing.

**Comment by stevermeister** [comment]
yes, true! thank you!
but still it's good to use local packages instead of global - https://github.com/preboot/angular-webpack/pull/23/files
