### ISSUE TITLE
npm run docs generates typings errors

### ISSUE THREAD

**Issue by Gideonnn** [preboot/angular-webpack#228]
When I run `npm run docs` this error appears:

```
Error: D:/path/to/project/node_modules/@angular/core/src/application_init.d.ts(15)
 Cannot find name 'Promise'.
```

There are also errors that say Map and Set cannot be found.

If I add `/// <reference path="../node_modules/typescript/lib/lib.es6.d.ts" />` to the entry file, they are gone. If I am right this is the old way of referencing typings. What is the 'new' way to do this?

**Comment by Foxandxss** [comment]
Good question.

I never used typedocs to be honest, Olivier put that when he created this but I never gave it any extra thought. I will investigate it tho and come back to you.

**Comment by yangbin1994** [comment]
"target": "ES5" => "target": "ES2015"
but i dont know why

**Comment by Gideonnn** [comment]
@yangbin1994 Because Promise, Map and Set are ES2015 standard. Though I don't think it is a fix because it should include typings anyway.

**Comment by mcescalante** [comment]
When I run `npm run docs` with the latest code, these issues seem to have been resolved, and I am getting a successful doc generation without any warnings or errors. Closing this, but comment if you run into these issues with the latest commit.
