### ISSUE TITLE
"declaration": true in tsconfig.json

### ISSUE THREAD

**Issue by andrea-spotsoftware** [preboot/angular-webpack#235]
Why adding `"declaration": true` in tsconfig.json "compilerOptions": {}  and running:

`npm run build`

won't let the **angular2-template-loader** writing templates and css inline in dist/app.js?

With `"declaration": false` everything works.

**Comment by andrea-spotsoftware** [comment]
I think that this should be the problem. 
There is also a solution provided, but it's not working for me.
https://github.com/TheLarkInn/angular2-template-loader/issues/19

**Comment by mcescalante** [comment]
I just added `"declaration": true` to my compilerOptions and successfully built the project with no warnings or errors. Something probably updated upstream since then. Going to close this, but feel free to comment if you are still seeing this issue with the latest changes.
