### ISSUE TITLE
http request fails

### ISSUE THREAD

**Issue by syeddk** [preboot/angular-webpack#245]
Hi Team, 

I am trying to make a call to static json using http module, having trouble loading data from JSON using http. Also tried with API call still no luck. Any help is appreciated.

**Comment by MadhuJutur** [comment]
So am i facing above issue, please help

**Comment by syeddk** [comment]
Even I tried with Observables, guys need help here

**Comment by Foxandxss** [comment]
I am the sole maintainer of this repository and I also have a dayjob to attend. A little patience.

**Comment by syeddk** [comment]
@Foxandxss , Thank you

**Comment by hijoncon** [comment]
@syeddk you can put your json file under public folder. And you can call it /filename.json

Other option: you can create a get call under webpack dev server. Via app.use then you can filter either req.method

**Comment by syeddk** [comment]
Hi @hijoncon, Thank you for the reply.
I will be a little more clear with my issue, please have a look at the scenario. 

Here is my code 
```
rs.service.ts (Service)
---------
getRulesets (): any {
       this.http.get('/rulesets.json').map((res:Response) => res.json());  
}
```   

```
rs.component.ts (Component)
------------------
 this.rulsetService.getRulesets().subscribe(content => this.staticJsonData = content);
```

And getting an issue mentioned below
![image](https://cloud.githubusercontent.com/assets/11690208/20421197/749b67b0-ad88-11e6-8178-c537a8e88ec7.png)

What am I doing wrong?

**Comment by ollwenjones** [comment]
You need to make sure that `rulesets.json` is in a folder which is in/with other statically served assets.

**Comment by syeddk** [comment]
Thanks @ollwenjones ,

Now i am getting 'undefined'. 
Even i am getting for REST API calls as well
can any one help out.

**Comment by mcescalante** [comment]
@syeddk do you still need help with HTTP services with Angular? If so, post your latest code here and I can try to help you debug it and make it work.
