### ISSUE TITLE
Error running test

### ISSUE THREAD

**Issue by trusktr** [preboot/angular-webpack#25]
I created a project and built off of this starter, but when I try to run my first test:

```js
import app from './app.module'; // set up the app module.
import './globalservices/someService'; // register the service onto the 'app' module.

describe('someService', () => {

  let service;

  beforeEach(() => {
    angular.mock.module('app');

    angular.mock.inject(_someService_ => {
      service = _someService_;
    });
  });

  it('service should exist.', () => {
    console.log(service);
    return;
  });

});
```

I get an error like

```
❯ npm run test

> angular-webpack-workflow@1.0.0 test /Users/trusktr/src/refuel4+sme-onboarding
> karma start

05 05 2016 22:22:53.200:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
05 05 2016 22:22:53.245:INFO [launcher]: Starting browser PhantomJS
05 05 2016 22:22:58.348:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Connected on socket /#LzaJexxVlI1wyYJ5AAAA with id 1411457
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  ReferenceError: Can't find variable: Map
  at undefined:14
```

Perhaps one of the files I imported eventually imports something that use `new Map`, but, as you can see the error isn't helpful at all (no idea where this happens). Any thoughts?

**Comment by trusktr** [comment]
Alright, I removed the import statements, so it's like this:

```js
describe('ENV', () => {

  console.log(' --- 1');

  let ENV;

  beforeEach(() => {
    console.log(' --- 2');
    angular.mock.module('app');

    console.log(' --- 3');
    angular.mock.inject(_ENV_ => {
      console.log(' --- 4');
      ENV = _ENV_;
    });
  });
  console.log(' --- 5');

  it('ENV should exist.', () => {
    console.log(' --- 6');
    console.log(ENV);
    return;
    //expect(ENV.url).toBe('https://github.com/preboot/angular-webpack');
  });
  console.log(' --- 7');

});
```

The output is

```
 --- 1
 --- 5
 --- 7
```

So, something is causing this error that seems to be outside of my code.

**Comment by Foxandxss** [comment]
I just tried a fresh copy and works, but I can asume that it is somehow requesting es6-shim for you. I will research because I think there were some changes lately on babel world.

**Comment by Foxandxss** [comment]
Could you try installing `es6-shim` and `require()` it at top of the tests.webpack.js file?

**Comment by trusktr** [comment]
@Foxandxss That worked! But, should this be handled with Webpack+Babel? Maybe there's something else to use in place of es6-shim that relates to Babel? Or is es6-shim better for some reason?

**Comment by trusktr** [comment]
I just got

```
        ReferenceError: Can't find variable: Symbol (line 22)
```

in another file. Do I need to import es6-shim in all of them?

**Comment by Foxandxss** [comment]
I will try to try it tomorrow and see what is going on. But normally adding it once at test.webpack.js should do the trick.

**Comment by trusktr** [comment]
I believe this started happening once I added a `for..of` loop, which when transpiled by Babel uses `Symbol.iterator`.

**Comment by trusktr** [comment]
Let me try to find where it happens in the compiled code...

**Comment by trusktr** [comment]
Here's a more full error:

```
        ReferenceError: Can't find variable: Symbol in /Users/trusktr/src/refuel4+sme-onboarding/src/tests.webpack.js (line 67302)
```

Seems like the built files go into memory? How do we output to filesystem so we can see?

**Comment by Foxandxss** [comment]
You can run `node_modules/.bin/webpack` for that.

You probably need babel-polyfill. Will check that too.

**Comment by trusktr** [comment]
Yep, that was it: http://stackoverflow.com/a/35320045/454780

**Comment by trusktr** [comment]
So, after adding babel-polyfil, es6-shim no longer needed.

**Comment by leyayun** [comment]
I have the same problem.  The callback of angular.mock.inject did not execute. 
Here is my test file.
`import home from '../../src/app/home/';

describe('HomeController', () => {
  let ctrl;

  beforeEach(() => {
    console.log('beforeEach::');
    angular.mock.module(home);
    console.log('injectModule::');

    angular.mock.inject(($controller) => {
      ctrl = $controller('HomeController');
    });    
    console.log('injectHomeController::');
  });

  it('should contain the right title', () => {
    console.log('HomeController::', ctrl);
    expect(1).toBe(1);
  });
});`

The error message.
`LOG: 'beforeEach::'
LOG: 'injectModule::'
LOG: 'HomeController::', undefined
PhantomJS 2.1.1 (Mac OS X 0.0.0) HomeController should contain the right title FAILED
	forEach@/Users/aaron/demos/angular-webpack/test/tests.webpack.js:8446:25 <- webpack:///~/angular/angular.js:322:0
	loadModules@/Users/aaron/demos/angular-webpack/test/tests.webpack.js:12672:13 <- webpack:///~/angular/angular.js:4548:0
	createInjector@/Users/aaron/demos/angular-webpack/test/tests.webpack.js:12594:31 <- webpack:///~/angular/angular.js:4470:0
	workFn@/Users/aaron/demos/angular-webpack/test/tests.webpack.js:41951:61 <- webpack:///~/angular-mocks/angular-mocks.js:2954:0
	inject@/Users/aaron/demos/angular-webpack/test/tests.webpack.js:41931:47 <- webpack:///~/angular-mocks/angular-mocks.js:2934:0
	/Users/aaron/demos/angular-webpack/test/tests.webpack.js:42193:25 <- webpack:///test/home/home.spec.js:11:24
	/Users/aaron/demos/angular-webpack/test/tests.webpack.js:12712:54 <- webpack:///~/angular/angular.js:4588:0
PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 1 of 1 (1 FAILED) (0 secs / 0.00PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 1 of 1 (1 FAILED) ERROR (0.051 secs / 0.007 secs)`

**Comment by FrEaKmAn** [comment]
I have same error and no idea how to solve it.

**Comment by phra** [comment]
to solve this you can look at this [PR](https://github.com/preboot/angular-webpack/pull/44/)
if you use ES2015 and above you can just cherry-pick that commit to have a working component generator with tests automatically scaffolded.

**Comment by stefan-dimitrov** [comment]
I found a solution with my setup. The problem was one of two things:
- the inject() method cannot inject a particular dependency, and it fails **silently**. After manually finding the problematic dependency/ies and fixing it the inject() ran fine.
- another cause was also a previous module(...) call - the module fails to be loaded(also silently) and the dependencies for the inject() also fail, so in turn the inject() fails.
