### ISSUE TITLE
This angular2-webpack saved my day

### ISSUE THREAD

**Issue by calebeaires** [preboot/angular-webpack#252]
I have migrated my app to your ``angular2-webpack`` to check if this seed will get along with some module I am trying to use: KnexJS. Happly, it works.

Before this decision, I have tried to implement this module (KnexJS) with ``angular-cli`` / official angular quickstarter and [AngularClass](https://github.com/AngularClass/angular2-webpack-starter) starter. KnexJS module doesn`t works as expected on those starters.

```
npm install knex;
npm install @types/knex;
```

The problem I faced is explenaid on [stackoverflow question](http://stackoverflow.com/questions/40810825/browser-support-on-angular-cli-angular-2-with-webpack-to-knexjs). May you help us understand why those webpack starters dont work with this module as your ``preboot/angular2-webpack`` does very well.

Knex is an SQL ORM to node, but it can be built using a JavaScript build tool such as browserify or webpack. In fact, the [documentation from it](http://knexjs.org/) uses a webpack build.

**Comment by Foxandxss** [comment]
All the solutions named here (and my starter) are frontend starters and knex is a server side library. It is not supposed to be used on any of them.

**Comment by calebeaires** [comment]
Knex has function that let us create sql string with the use of toString(). So, there is a use on browser too. One use of it is to take advantage of websql.

**Comment by ollwenjones** [comment]
Forming database queries on the client-side sounds like a major security risk to me, or is websql a local storage thing? Looks like the W3C abandoned the spec in 2010.
