### ISSUE TITLE
Upgrade to Angular 2.3

### ISSUE THREAD

**Issue by kuldarim** [preboot/angular-webpack#257]
When you are planning to upgrade to Angular 2.3?

**Comment by Foxandxss** [comment]
We released angular 2 a few hours ago. I Will see if I can update it today, I have a 3 hours presentation for tomorrow and what I don't have is time :P

**Comment by jurasm** [comment]
@Foxandxss any updates on this?

**Comment by mcescalante** [comment]
This should be all set, bumped Angular to 4+ in https://github.com/preboot/angular-webpack/commit/0384b1254da188f3341358648a4e022ffa500aac
