### ISSUE TITLE
Set default port to some thing other than 8080

### ISSUE THREAD

**Issue by thekalinga** [preboot/angular-webpack#259]
Currently the default port is set to 8080, which is a default port for many web server in the java world.

If you need to run both the Java App & the sample side by side as first step to see if he can use this as the template, user need to remember to change the port to non-8080 in two different places in the source.

Can we change the default to some port other than 8080 to something more non-confrontational so that user's first experience would be much smoother

**Comment by hbweb** [comment]
Look into your package.json file in line 11 and change the port number 8080 to any port you wish
```
"server": "webpack-dashboard -- webpack-dev-server --inline --port 8080",
```

**Comment by thekalinga** [comment]
The whole point of my ticket is to say people need to know and change various scripts(dependending on the script they may want to use) in `package.json`.

Since 8080 perse has no intrinsic meaning w.r.t angular2/js, there is no pointing keeping it in conflict with known server port addresses atleast as default.

**Comment by Foxandxss** [comment]
8080 is widely used in the frontend as well.

You can change it in your project, I won't change it here, sorry. I am too used to 8080 and changing it will drive me crazy.

**Comment by vjarysta** [comment]
To extend @hbweb's answer, I would just add that you also have to edit the port in `webpack.config.js`, in `config.output.publicPath`.

```
  config.output = isTest ? {} : {
    path: root('dist'),
    publicPath: isProd ? '/' : 'http://localhost:4242/',
    filename: isProd ? 'js/[name].[hash].js' : 'js/[name].js',
    chunkFilename: isProd ? '[id].[hash].chunk.js' : '[id].chunk.js'
  };```

**Comment by kuncevic** [comment]
E.g in angular cli the default port is '4200' :) but on my main project changed it to '4201'. Also I have some projects using port 999, 9999 and 666. There is so much fun with a ports numbes :)

**Comment by mcescalante** [comment]
Since the port can be changed easily via line 11 `package.json` and there really isn't much to be fixed here, I am going to close this issue.
