### ISSUE TITLE
I Want to include extranal plugin 

### ISSUE THREAD

**Issue by anandangular** [preboot/angular-webpack#268]
How to include the external plugin in angular2?????????????
 
I m getting error after making dist of  my project .. please can you help me out to come out from this error 
...............

**Comment by warapitiya** [comment]
Try importing your external plugin from **src/vendor.ts** file.

**Comment by mcescalante** [comment]
This is a fairly generic issue and has been inactive for a few months now - I am going to close this. If you are still having issues with adding external dependencies to this project, feel free to comment here or open a new more descriptive issue 😄
