### ISSUE TITLE
I want to invlude the external html and css plugin and jquery plugin in my project

### ISSUE THREAD

**Issue by anandangular** [preboot/angular-webpack#269]
I m getting error on making dist of my project
npm ERR! Linux 4.4.0-53-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build:prod"
npm ERR! node v6.9.1
npm ERR! npm v4.0.2
npm ERR! missing script: build:prod
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR! https://github.com/npm/npm/issues
npm ERR! Please include the following file with any support request:
npm ERR! /opt/lampp/htdocs/angular/angular2-webpack-master (copy)/npm-debug.
I m geting this error
($ npm run build:prod ) wen i run this command to make dist of my project to upload in serve .... any body can help me out to come out from this problem ...
I have download the prokect (angular2-webpack-master ) and worked on this started kit now it gving while dist of the project to uplod in server

**Comment by ollwenjones** [comment]
`missing script: build:prod` makes it sound like either

* you are running from the wrong directory (not where `package.json` is located)
* you have modified package.json so there is no longer a build script named `build:prod`

?

**Comment by mcescalante** [comment]
Since this has been inactive for a few months, I am going to close the issue. There have been a number of updates since this was opened, so if you still have issues give a fresh clone a try and see if you have the same issues.
