### ISSUE TITLE
Global css don't get applied

### ISSUE THREAD

**Issue by plakak** [preboot/angular-webpack#27]
Hi,

When I put my sass files (or even CSS files) in src/style, and then run npm style no styles are getting applied to the whole project. Is there a special name/way I should do that?
I don't want to apply styles in components, just get all styles from src/style. 
I'm sure I'm doing something wrong, but can't where the problem is...

**Comment by Foxandxss** [comment]
You need to import them once (main file or something). Webpack has no way of knowing that you want them unless you import them.

**Comment by plakak** [comment]
Ah, thank you! Worked like a charm.
