### ISSUE TITLE
Use of webpack.config in another project - Stuck while building

### ISSUE THREAD

**Issue by Thisen** [preboot/angular-webpack#281]
I find your webpack config fitting my needs to a project and  I have therefore tried to use your webpack config in a project of mine: https://github.com/Thisen/angular-apollo-stack/

The change I have made has been to change 'src' folder to 'client' in the config.

The problem is the build gets stuck:

![image](https://cloud.githubusercontent.com/assets/10807938/22427086/0a44da32-e702-11e6-8df4-fdb8f5c286e7.png)

Is there a obvious reason to this? Thanks in advance.

**Comment by Foxandxss** [comment]
I don't see anything wrong at all in there. That is the desired output.

**Comment by Thisen** [comment]
It's stuck and doesn't finish. And it doesn't hash the files.

**Comment by ollwenjones** [comment]
Looks like the _development_ output... you get hashes in the filenames and emitted files for the _production_ build. I think you just have the dev server running there, maybe?
