### ISSUE TITLE
Build issue cannot npm run build successfully

### ISSUE THREAD

**Issue by jeremiahgibson91** [preboot/angular-webpack#282]
This might be lodash's fault or @types/lodash. I cloned your repo fresh and did npm install && npm run build.

Error from view in npm start
Cannot find namespace '_'.

Error from npm run build.
[at-loader] Checking finished with 140 errors
Error in bail mode: [at-loader] node_modules/@types/lodash/index.d.ts:11444:21 
    ']' expected.

npm ERR! Linux 4.8.0-34-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! app@0.0.0 build: `rimraf dist && webpack --progress --profile --bail`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the app@0.0.0 build script 'rimraf dist && webpack --progress --profile --bail'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rimraf dist && webpack --progress --profile --bail
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/j/Projects/angular2-webpack/npm-debug.log

**Comment by kayuda91** [comment]
Same error on Windows when try to run build

**Comment by kayuda91** [comment]
I found solution. Just add to package.json in devDependencies -
`"typescript": "~2.1.5" ` - upgrade typescript version and if you need in file tsconfig.json change
```
"noUnusedLocals": true,
"noUnusedParameters": true
```

to
```
"noUnusedLocals": false,
"noUnusedParameters": false
```
With this parameters may be errors on unused variables in your components.

**Comment by freps** [comment]
+1 Had the same problem. 
@kayuda91 your fix also solved my problem.

**Comment by Foxandxss** [comment]
Typescript 2.1.x is not a solution right now because it doesn't work with AOT until Angular v4.

If those params is giving grief, better delete them.

**Comment by mcescalante** [comment]
I think that with the Angular 4 & Typescript 2.2.1 bump (https://github.com/preboot/angular-webpack/commit/0384b1254da188f3341358648a4e022ffa500aac), this should be all set
