### ISSUE TITLE
Not able to run the mermaidAPI.js in IE09 rather I can view the result in chrome

### ISSUE THREAD

**Issue by Sujith1715** [preboot/angular-webpack#288]
<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm1.aspx.cs" Inherits="WebApplication1.WebForm1" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <link rel="stylesheet" href="Scripts/mermaid.css" />
    <script type="text/javascript" src="Scripts/mermaidAPI.js"></script>
        function test() {
            var element = document.querySelector("#graphDiv");
            var insertSvg = function (svgCode, bindFunctions) {
                element.innerHTML = svgCode;
                bindFunctions(element);
            };
            var graphDefinition = 'graph TB\na-->b';
            var graph = mermaidAPI.render('graphDiv', graphDefinition, insertSvg);
        };
        window.onload = test;
    </script>
</head>
<body>
    <div class="mermaid">
        CHART DEFINITION GOES HERE
    </div>
    <div class="mermaid" id="graphDiv">
    </div>
</body>
</html>

**Comment by Foxandxss** [comment]
Are you sure this is the right repo for this?

**Comment by Sujith1715** [comment]
Yes

**Comment by Foxandxss** [comment]
Uhm, so I don't know what to say. What I see in there is a bunch of WebForms code (which I thought it deprecated like years ago) and no Angular v2 nor webpack in there.

**Comment by mcescalante** [comment]
Going to close this because of inactivity and lack of details.
