### ISSUE TITLE
I wonder how to use scope in this workflow ?

### ISSUE THREAD

**Issue by leyayun** [preboot/angular-webpack#29]
How to work with scope in this workflow?

**Comment by Foxandxss** [comment]
You can always inject $scope. On the other hand, there is no reason to do that

**Comment by phra** [comment]
@leyayun look at (this)[https://docs.angularjs.org/guide/component#comparison-between-directive-definition-and-component-definition].
scopes are being deprecated in favor of isolated components and 1-way data flow. (e.g. angular2 doesn't have scope concept)
