### ISSUE TITLE
Rename project name, "Just Angular" :)

### ISSUE THREAD

**Issue by Chyngyz** [preboot/angular-webpack#299]
It would be great to rename the project :)
My suggestions are:

- ngx-webpack-seed
- angular-webpack
- angular-webpack-seed

These names that are not in our [awesome-angular-components](https://github.com/brillout/awesome-angular-components#starter-kit) starter kit list.

**Comment by Foxandxss** [comment]
I have a list of things to do in here. I will probably rename the angular 1 one to `preboot/angularjs-webpack` and this one to `preboot/anguñar-webpack`.

But perhaps I can't since the old one is already `preboot/angular-webpack`.

**Comment by Chyngyz** [comment]
`preboot/anguñar-webpack` sounds interesting 👍 

Thanks for the great starter kit by the way. Use it in several projects.

**Comment by Foxandxss** [comment]
That was a typo 😂

**Comment by Chyngyz** [comment]
Oh 😂,  one more variant.
