### ISSUE TITLE
Image paths not being parsed

### ISSUE THREAD

**Issue by ronnieoverby** [preboot/angular-webpack#31]
```HTML
<main>
  <h1 class="title">Hello from Angular !</h1>

  <!-- Images (and assets) are parsed and loaded from within the public directory -->
  <img src="/img/logo.png">
</main>
<footer>
  <a ng-href="{{app.url}}">Webpack Angular Starter</a>
</footer>
```

The comment leads one to believe that webpack will modify the src attribute value, but I don't see any evidence that this is happening or is configured to happen.

I need this and I'm new to webpack, so I thought I'd ask you about it.

**Comment by Foxandxss** [comment]
Webpack will move the content (with CopyWebpackPlugin) from `/public` to `/dist` so at the end you will have the same paths both in development and production.

**Comment by ronnieoverby** [comment]
I'm sorry but I don't get it...

This has been my greatest frustration with webpack: you're encouraged to use some kind of a dev-server at development time that can server files from memory. While I'm sure this works great for people that either don't have a backend server or are using node as their backend, the rest of us building our apps on .NET, Python, Go, Ruby, etc... we have to find some way during development to get resources from this webpack dev server... it's such a pain.

So I have my Asp.Net app running it's server and your webpack starter is running via `npm start`. I have my web app configured during development to request all static asset files from http://localhost:8080/. This is working except for the case where a template has an image ref, a la: `<img src="/img/logo.png">`

Now, what I'm lead to believe is that webpack will see that path and ought to "rewrite" the html to be:
`<img src="http://localhost:8080/img/logo.png">` but it's not.

I'm trying to take that desired behavior and the comment in the app.html file and also your last reply,"Webpack will move the content (with CopyWebpackPlugin) from /public to /dist so at the end you will have the same paths both in development and production," and reconcile all of this to something that will finally let me move on and actually build my application instead of fighting with webpack, but things are not going well for me.

You can probably tell I'm frustrated.

**Comment by Foxandxss** [comment]
I hear you friend.

You shouldn't mix your backend (ASP.NET) with your frontend application. You better go with a completely separate project for ASP.NET (with ASP.NET server) and a completely separate project (and separate folder) for the angular application, using webpack and its server.

That will remove some frustration in the long term. Mixing backend and frontend is a call for problems.

Or perhaps I understood you wrong.

**Comment by ronnieoverby** [comment]
I think agree. Separating them adds some complexity to the deployment process, but I think it's less complexity overall.
