### ISSUE TITLE
Using Yeoman generator. Versions of generator.

### ISSUE THREAD

**Issue by NechiK** [preboot/angular-webpack#324]
Hello, guys! You make nice work of releasing generator.
However, why you don't use Yeoman for it? So that developers have a possibility to install it by NPM, choose version of generator (which will contain inside required Angular version) instead of pulling repository, see your commits etc.

**Comment by Foxandxss** [comment]
I had so many bad experiences with it and its generators that I never considered that.

I am closing this because I don't think I am going to do that.

**Comment by ollwenjones** [comment]
A basic yeoman generator is easy to setup, but maintaining a good & thorough one is non-trivial. FWIW, I _think_ I ran across one that references this config, @NechiK, you could ook for that.
