### ISSUE TITLE
Simple clone and npm start will start the server, but browsing to localhost:8080 results in nothing

### ISSUE THREAD

**Issue by mariocatch** [preboot/angular-webpack#33]
When I clone, `npm install` and then `npm run start`, I get the following output:

```
λ npm run start

> angular-webpack-workflow@1.0.0 start C:\dev\me\angular-webpack
> npm run server


> angular-webpack-workflow@1.0.0 server C:\dev\me\angular-webpack
> webpack-dev-server --history-api-fallback --inline --progress

 70% 1/1 build moduleshttp://localhost:8080/
webpack result is served from http://localhost:8080/
content is served from ./src/public
404s will fallback to /index.html
chunk    {0} app.bundle.js (app) 1.38 MB [rendered]
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 303 bytes [rendered]
webpack: bundle is now VALID.
```

When I browse to http://localhost:8080, I get:
![image](https://cloud.githubusercontent.com/assets/1885172/16084348/79c681ec-32e6-11e6-8f31-51707815d7d2.png)

I haven't changed anything. The server seems to be running (no errors in console output). Any ideas?

Edit:

I'm on Windows 7.

**Comment by Foxandxss** [comment]
Weird, makes no sense.

**Comment by mariocatch** [comment]
@Foxandxss I agree :) Any other sort of debuggin

**Comment by Foxandxss** [comment]
You don't have anything running in that port?

**Comment by mariocatch** [comment]
Well, even though Windows is stating nothing is running on port 8080, if I change the npm `server` script and add `--port 7777` to the `webpack-dev-server` command, then it works. So it's a non-issue, and something is screwy on my 8080 port.

Sorry and thanks for the assistance.
