### ISSUE TITLE
remove semicolons

### ISSUE THREAD

**Issue by phra** [preboot/angular-webpack#331]
hi,

i'm now writing most of my code without the [semicolons](http://www.bradoncode.com/blog/2015/08/26/javascript-semi-colon-insertion/). (actually all of it!)
it would be nice to remove them and change the tslint config accordingly.
what do you think about this guys?

**Comment by Foxandxss** [comment]
Definitely, not.

**Comment by phra** [comment]
btw this kind of style is enforced by [standard](https://standardjs.com/).

**Comment by Foxandxss** [comment]
Yes, I know standard but I don't really like to develop without semicolons. I use them at work and that would confuse the heck out of me.

**Comment by phra** [comment]
@Foxandxss in the beginning i was very doubtful about writing code without semicolons, i started with C language at university, so it was very uncomfortable for me. btw right now that is a while that i write js code without semicolons, i prefer it **DEFINITELY** in this way. just my 2 cents.

**Comment by Foxandxss** [comment]
Yes, me too, but when the 100% of the projecs your work with use semicolons, I don't want to get used to not write them and then forget when I need them.

**Comment by phra** [comment]
@Foxandxss maybe you can just write a webpack loader that inserts semicolons. 😆 [actually not a so bad idea]

**Comment by Foxandxss** [comment]
No loader would add code to your code.
