### ISSUE TITLE
How can I show full error details when there is a ts error ?

### ISSUE THREAD

**Issue by ohadinho** [preboot/angular-webpack#333]
Hi,
I've cloned this project, npm installed and hit "npm start".
After i've made an error in one of my typescript files - i've received this error on console:
"[at-loader] Checking finished with 2 errors"

How can I show the full error description ?

Thanks.

**Comment by Foxandxss** [comment]
copy and paste those 2 errors.

**Comment by ohadinho** [comment]
Hi,
What do you mean ?
My goal is to show full description of errors in the console.

Thanks.

**Comment by JunkyDeLuxe** [comment]
Hi, you will see those errors in your web browser (console chrome for example)

**Comment by mcescalante** [comment]
Open the website in a web browser (Chrome or Firefox recommended) and open the Developer Tools. You can do this in chrome via `View > Developer > Developer Tools`. Then, click the "Console" tab. Your errors with full traceback should be there.

![Imgur](http://i.imgur.com/H5mKiOU.png)

**Comment by ohadinho** [comment]
Capish.
Thank you guys
