### ISSUE TITLE
restore repository

### ISSUE THREAD

**Issue by phra** [preboot/angular-webpack#336]
@preboot/collaborators @Foxandxss sorry, i've copied the wrong upstream. can someone push force to restore the history of the repository? SORRY VERY MUCH! :cry:

**Comment by Foxandxss** [comment]
NEVER do a force push and this won't happen.

**Comment by phra** [comment]
sorry, i was scaffolding a new project. :sob:

**Comment by Foxandxss** [comment]
That is still not an excuse to do a force push :)

**Comment by phra** [comment]
at least if was freshly cloned before the push. sorry again.
