### ISSUE TITLE
What is the simplest, most straightforward manner of including CSS preprocessor?

### ISSUE THREAD

**Issue by stefek99** [preboot/angular-webpack#34]
Some reading: http://angular-tips.com/blog/2015/06/using-angular-1-dot-x-with-es6-and-webpack/

![screen shot 2016-06-23 at 22 43 54](https://cloud.githubusercontent.com/assets/249703/16321386/748d5d86-3994-11e6-8658-c245444eda60.png)

Having a look at the list of features:
![screen shot 2016-06-23 at 22 44 22](https://cloud.githubusercontent.com/assets/249703/16321412/97930952-3994-11e6-92fd-6f7f58c41ff0.png)

Having look at the source code: https://github.com/preboot/angular-webpack/blob/master/webpack.config.js#L97-L102

---

I put a `test.scss` file into `style` directory and the styles wasn't applied.

```
body {
  a {
    color: red;
  }
}
```

My experience with WebPack so far - it combines all `.js` into a single `app.bundle.js` - I would like to have same feature for the styles... Before I start reinventing the wheel - is it a matter of changing some settings in CSS loader, or maybe adding some other loader such as: https://github.com/jtangelder/sass-loader ?

Or maybe it is working all the time, it's just me not naming files correctly, not importing them?

---

I can confirm that `test.css` is working just fine while `.scss` fails to load:
![screen shot 2016-06-23 at 22 55 05](https://cloud.githubusercontent.com/assets/249703/16321587/a9558344-3995-11e6-98bf-d8fe60379c23.png)

**Comment by phra** [comment]
just follow `README.md` of the selected loader for webpack, like [this one](https://github.com/postcss/postcss-loader)
