### ISSUE TITLE
npm start not work

### ISSUE THREAD

**Issue by centny** [preboot/angular-webpack#351]
i am new to webpack, flowing blew command:
npm install
npm start

![image](https://user-images.githubusercontent.com/4049551/28195354-424f9254-687c-11e7-8e6e-e3b0a601ff1d.png)

but the browser is:

![image](https://user-images.githubusercontent.com/4049551/28195365-5470d3c6-687c-11e7-9187-eb718e51eaea.png)

what i missing.

**Comment by patricknazar** [comment]
I have the same issue but it get's stuck on "Loading..." console error from zone.js 

angular/zone.js#832

**Comment by centny** [comment]
it is my problem, i start another process on 8080,
