### ISSUE TITLE
How to build it minification safe?

### ISSUE THREAD

**Issue by stefek99** [preboot/angular-webpack#39]
Trying to figure it out right now:

* https://www.reddit.com/r/angularjs/comments/3yv2zp/webpack_and_production_minification_best_practices/
* http://thegreenpizza.github.io/2013/05/25/building-minification-safe-angular.js-applications/
* https://docs.angularjs.org/guide/di#dependency-annotation

**Comment by Foxandxss** [comment]
I personally use $inject for that.

**Comment by phra** [comment]
you can use this [plugin](https://www.npmjs.com/package/ng-annotate-webpack-plugin) for webpack or instead use [$inject](https://docs.angularjs.org/guide/di/#-inject-property-annotation) annotation.

**Comment by stefek99** [comment]
YEAH...

Would be nice to make it min-safe by default...

In fact I regret starting my project with you - the main reason why I use starter projects / seeds / defaults is because I don't like configuring stuff. Convention over configuration, less effort wasted doing repetitive stuff, more mental bandwidth for stuff that matters.

#32 
#35 
#36 

And I also had a few emails back and worth with owner of the project who is also not interested in maintaining it... All in all - I advise against using it.

**Comment by escapedcat** [comment]
Is this also the reason why [`webpack -p` (for v1 it was also `--production`)](https://webpack.js.org/guides/production-build/) isn't used?   
Because this would use default Uglify options which might not work with angular?  
Sorry if this is off-topic.
