### ISSUE TITLE
Why autoprefixer not working?

### ISSUE THREAD

**Issue by Chooin** [preboot/angular-webpack#40]
I have seen config for postcss loader, but when I run build, no prefix added for crossing browser.

**Comment by phra** [comment]
@Chooin  if i have spear time, i'll look into this. ;)

FYI: i'm sending various PRs to this project but imho @Foxandxss doesn't want to add too much opinions, so maybe in the future i'll maintain an updated [fork](https://github.com/phra/angular-webpack/) with more opinions than this one.

**Comment by Foxandxss** [comment]
I will check the issue.

Sorry, I have too many projects to maintain and to be sincere, this is not top on my list :/

But yes, I don't want too much opinions.

**Comment by phra** [comment]
@Foxandxss if you want some help to maintain this project, i'm available to help. ;)

**Comment by Foxandxss** [comment]
I am all in for help, but you want to put some opinions that I personally don't see (like the generator, I am completely against them :/)

**Comment by phra** [comment]
@Foxandxss as i said before, i'll keep the opinions on my fork.

**Comment by phra** [comment]
i appreciate very much @Foxandxss 's starter kits and i definitely think that i will use these ones for my future angular1.5 and angular2 projects.
if you want add me to preboot organization so i can start to manage opened issues. (no opinions, only maintenance of the project, as updating deps, managing open issues, et cetera and i'll keep a personal fork with my opinions on a dedicated branch or branches with different flavours of opinions)
or maybe you prefer to review some work before adding me to preboot org?

let me know what you think about it so i can start to help you. ;)

**Comment by Foxandxss** [comment]
I added you. Please create some PRs to fix the issues you see so we can discuss that stuff :)
