### ISSUE TITLE
Requiring all spec files with es5 syntax

### ISSUE THREAD

**Issue by graemegeorge** [preboot/angular-webpack#42]
Whilst using this seed with es5 only syntax, I tried to require each spec file in the `tests.webpack.js` file in the following way, hoping it would work. It comes back with an error on almost every file, scss, js, html etc.. I only have one spec file so far and since `test` only came back as one path, I assumed it would include that one path? What's going on here, am I missing something? 

```
require('angular');
require('angular-mocks/angular-mocks');

var testsContext = require.context(".", true, /.spec$/);
testsContext.keys().forEach(function(test) {
  require(test);
});
```

**Comment by phra** [comment]
just drop old ES5 syntax and learn ES2015/2016/2017. you can see how to use it looking at this [PR](https://github.com/preboot/angular-webpack/pull/44/commits/b349b0e9bd2ce4e5b6288568f08d67b224fbbf7d).
you can cherry-pick that commit or can compile by hand that template.

PS: babel convert imports/exports to commonjs format by default, so if you still want to use ES5 you can convert that template to cjs format (you can compile w/ babel to see how the module in ES5 needs to be)

**Comment by graemegeorge** [comment]
I know ES6 already. I would love to use it but the decision is not mine in this scenario. Thanks anyway

**Comment by phra** [comment]
@graemegeorge eheh, i know that feeling. i'm sorry about that. ;)
