### ISSUE TITLE
How to user 3rd party typings?

### ISSUE THREAD

**Issue by gdipkf1986** [preboot/angular-webpack#43]
I tried to add google api scripts by "typing install dt~gapi", it added to typings folder, but after that i have no idea how can i import the gapi in app folder, like 
```javascript
const gapi = <gapi>window['gapi']; // here will show error gapi is not defined, so cant convert window.gapi to gapi, what should i do?
```

**Comment by phra** [comment]
you have to create a typings.json config via `typings init`, install dependencies via `typings install` and configure your IDE to use typings (e.g. vscode wants a [jsconfig.json](https://code.visualstudio.com/docs/languages/javascript) in order to enable intellisense)
