### ISSUE TITLE
update to new isparta loader

### ISSUE THREAD

**Issue by phra** [preboot/angular-webpack#47]
the actual [isparta-instrumenter-loader](https://github.com/ColCh/isparta-instrumenter-loader) has been deprecated in favor of [isparta-loader](https://github.com/deepsweet/isparta-loader).

we have to switch to the new loader.

**Comment by phra** [comment]
i think we can safely merge #48 without side effects.

**Comment by OmgImAlexis** [comment]
`npm WARN deprecated isparta-loader@2.0.0: This package is deprecated in favor of istanbuljs/babel-plugin-istanbul`

Should this be updated again?

**Comment by phra** [comment]
@OmgImAlexis thanks for the info. i'll look into this later.
