### ISSUE TITLE
isparta-loader is deprecated, replace with babel-plugin-istanbul?

### ISSUE THREAD

**Issue by McGiogen** [preboot/angular-webpack#51]
As from isparta-loader's readme, it is deprecated in favor of babel-plugin-istanbul.
I've made this change in my own project but I'm not sure I've done it correctly.
I can make a pr but I need an help to be sure it is all correct.

**Comment by phra** [comment]
hi @McGiogen,

please send a PR with your changes. if everything is working we'll merge that PR.

thanks for you time.

**Comment by McGiogen** [comment]
I've forked and done [some work](https://github.com/McGiogen/angular-webpack/commit/23ce44ef9e7c8b9561f1ae22a3ad1da29f1ad34a). The problem now is that I don't know how to count every test file, my configuration is counting only the entry point, tests.webpack.js.

Tomorrow I will try to fix it.

**Comment by McGiogen** [comment]
I think the work is done. Coverage has changed, but it was expected (as said in documentation...)

### Before:
=============================== Coverage summary ===============================
Statements   : 95.24% ( 20/21 ), 1 ignored
Branches     : 100% ( 6/6 ), 2 ignored
Functions    : 75% ( 3/4 )
Lines        : 92.31% ( 12/13 )

### Now:
=============================== Coverage summary ===============================
Statements   : 85.71% ( 6/7 )
Branches     : 100% ( 0/0 )
Functions    : 50% ( 1/2 )
Lines        : 85.71% ( 6/7 )

**Comment by phra** [comment]
@McGiogen why did the coverage change?

**Comment by phra** [comment]
nope, the PR is totally wrong. you have to drop crossenv and whatever you added and use only the webpack plugin.

**Comment by McGiogen** [comment]
Next monday I'll improve it and I'll check about coverage percentage

**Comment by phra** [comment]
i think that #53 is a proper fix for this issue. i will check later, eventually merging #53 and closing #52 .

**Comment by McGiogen** [comment]
I've updated the code in my pull request, now there is no more the dependency cross-env and every config the plugin needs is wrote in webpack.config.js. I used a temporary variable to be more consistent with the file style but obviously you can write the same using differents approaches.

**Comment by phra** [comment]
when i said to use a webpack plugin i meant to use a **webpack** plugin, not a **babel** one!
in this way it's not possible to have a consistent coverage when using differents loader such as typescript along with babel. see the other PR to understand, it uses an loader-agnostic instrumenter to calculate coverage!

**Comment by McGiogen** [comment]
Well, you already have your pull request with a webpack plugin but "everyone" on the internet seems to want to use babel-plugin-istanbul. I repeat that I'm not an expert of tests but I've read a lot and;
 - isparta-loader is deprecated **in favour of** babel-plugin-istanbul;
 - in the [last issue](https://github.com/deepsweet/istanbul-instrumenter-loader/issues/33) of istanbul-instrumenter-loader they say "looks like https://github.com/istanbuljs/babel-plugin-istanbul is a simpler solution at this moment." and "The babel-plugin does exactly the same as the loader does.".
This is why I thought that babel-plugin-istanbul could be a good idea.

In any case I opened the issue also to receive help so if you said that a webpack plugin is better I will believe you and I will continue to read to understand why (I don't have much time to spend so I'm a bit slow doing that).

**Comment by deepsweet** [comment]
sorry for confusing you guys. I just undeprecated isparta-loader back because new istanbul stuff is not completely ready yet.

**Comment by phra** [comment]
closed via #53.
