### ISSUE TITLE
Hit breakpoint on page refresh in browser dev tools?

### ISSUE THREAD

**Issue by BrainCrumbz** [preboot/angular-webpack#57]
When serving in development mode (`npm start`), one can open browser on `http://localhost:8080/` and its dev tools, then set a breakpoint, e.g. in [home.ts#ngOnInit()](hhttps://github.com/preboot/angular2-webpack/blob/master/src/app/components/home/home.ts#L18). When reloading page, execution should pause on that line.

Breakpoint seems to be ignored, although console shows logged message. Execution proceeds beyond that. Client app runs normally, no particular errors.
- HEAD: https://github.com/preboot/angular2-webpack/commit/59ea711fae0ee54829f7cc8c113ced658a3ff289
- Angular version: 2.0.0-beta.9
- Browser: Chrome 49.0.2623.87 m

**Comment by danmo** [comment]
Any resolution on this ? having the same issue

**Comment by Foxandxss** [comment]
I didn't saw this issue before. Sadly I am not really into debugging in browser like that. I will research it tho.

**Comment by BrainCrumbz** [comment]
Haven't tested it recently, but the culprit should be the webpack configuration `devtool`. Setting it to `source-map` seems to make breakpoints work.

**Comment by Foxandxss** [comment]
Ah, that makes sense. I need to re-visit the devtool for all three environments.

**Comment by BrainCrumbz** [comment]
@Foxandxss out of curiosity, how do you usually debug that client side code?

**Comment by Foxandxss** [comment]
console.log, yes kill me now.

**Comment by BrainCrumbz** [comment]
![munch_200px](https://cloud.githubusercontent.com/assets/3185573/14600548/7cff5a5c-055d-11e6-9591-feac871c978f.jpg)

**Comment by danmo** [comment]
:)

**Comment by Foxandxss** [comment]
I can't make that work with typescript loaders and sourcemaps. I don't know which library is having the problem.

**Comment by BrainCrumbz** [comment]
This is our home-made starter project, [YANGTSE](https://github.com/BrainCrumbz/YANGTSE), it has less features than yours and others as well. Last time we tried, at least, breakpoint worked. In case, `./webpack.common.js` and `./webpack.config.dev.js` are the guys.

**Comment by Foxandxss** [comment]
Will try.

I am more worried because if you put an error or something inside a component like:

```
class AppComponent {
  constructor() {
    foo(); // Doesn't exist
  }
}
```

The sourcemaps doesn't work correctly. Putting an error outside angular (bootstrap.ts for example) will work right. Need to investigate that too.

**Comment by BrainCrumbz** [comment]
I see. When we did our tests, we tried just that (*inside*) and it worked ... like setting a breakpoint on class member initialization, or within a component constructor, in an injectable service, etc.

**Comment by Foxandxss** [comment]
Nah, not talking about breakpoints in this case, just the sourcemaps being problematic. But that is another topic.

**Comment by BrainCrumbz** [comment]
Just to say that, from what I experienced, the two are quite related

**Comment by khmyznikov** [comment]
@BrainCrumbz @Foxandxss How i can debug in chrome dev tools? I saw only compiled js files or ngfactory.js files. I have tried add sourse-map options, but it does nothing.
