### ISSUE TITLE
How to include eslint for angular?.

### ISSUE THREAD

**Issue by pyella** [preboot/angular-webpack#60]
First I am new to webpack and my knowledge is limited.Is there any way I can incorporate eslint while running in webpack?. If so what all changes I need to make to webpack config file. Also I noticed my debug points in chrome are not getting hit, Am I missing something here?.

**Comment by phra** [comment]
hi,

you can look at this https://github.com/MoOx/eslint-loader loader for webpack. in the readme you can see the usage and installation.

cheers.
