### ISSUE TITLE
Will you update this starter for Webpack 2 ?

### ISSUE THREAD

**Issue by RPDeshaies** [preboot/angular-webpack#65]

**Comment by Foxandxss** [comment]
I guess I should. I haven't worried about Angular 1 or this starter for ages :/

**Comment by RPDeshaies-playster** [comment]
Ok ! I'm currently working on a angular 1 app and I want change its gulp build process to webpack 2.

I'm using your starter as an inspiration ;)

**Comment by Foxandxss** [comment]
I guess it still have a lot of users, it is just the need of focusing in less things

**Comment by mikeerickson** [comment]
Want a PR?

**Comment by Foxandxss** [comment]
Be my guest sir.

**Comment by mikeerickson** [comment]
@foxandxss sounds good, will do 🤓

**Comment by mikeerickson** [comment]
@Foxandxss All done, but need to attend a meeting.  I will PR when I get back
@RPDeshaies @RPDeshaies-playster

**Comment by phra** [comment]
if we are done, we can safely close this ticket.
feel free to reopen in case, @mikeerickson
