### ISSUE TITLE
getting error on fresh install

### ISSUE THREAD

**Issue by dcartertwo** [preboot/angular-webpack#7]
on fresh clone and install getting this error
```
ERROR in ./src/app.js
Module parse failed: /Users/danielcarter/Documents/code/bachman/node_modules/babel-loader/index.js!/Users/danielcarter/Documents/code/bachman/src/app.js Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import angular from 'angular';
|
| angular.module('app', []);
 @ multi app
```

**Comment by Foxandxss** [comment]
Are you using the latest version? With babel 6 update, there is an extra package to install (the presets) with extra configuration.

But a fresh clone, npm install and running it with `npm run dev` should do the trick.

That error of yours is because babel is not understanding `import` and that can be due to babel 6 missing presets.

**Comment by dcartertwo** [comment]
yeah, looks like i didn't have the babel-cli installed.  would you merge a pr that i make which edits the readme to add instructions about the global installs? i know its not necessary but could be helpful for people like me who are just hopping into the webpack/babel-sphere.

**Comment by Foxandxss** [comment]
Babel cli is not needed. Babel cli is to be able to compile files by hand on the terminal.

**Comment by dcartertwo** [comment]
i'm not sure, but installing the babel-cli was the only way i got rid of the error from a fresh install.

**Comment by Foxandxss** [comment]
I don't have it installed.

**Comment by itomas** [comment]
Maybe you missed .babelrc file. Check it :)

**Comment by phra** [comment]
this issue has no sense.
no need to have installed babel-cli for building w/ webpack.
you are missing something.
you can look at this [PR](https://github.com/preboot/angular-webpack/pull/44/) to see how to declare components ready to be imported.
