### ISSUE TITLE
Check coverage when a directory has no tests

### ISSUE THREAD

**Issue by Foxandxss** [preboot/angular-webpack#8]
Seems like having directories without tests makes the plugin ignore it.

**Comment by phra** [comment]
it seems that [isparta-instumenter-loader](https://github.com/ColCh/isparta-instrumenter-loader) has been deprecated. we have to update deps definition and webpack config to use the new [isparta-loader](https://github.com/deepsweet/isparta-loader).

i'll look into this.

**Comment by phra** [comment]
bug confirmed also with the new loader. it needs more investigation.

**Comment by phra** [comment]
i've found the problem.

tests are executed via require.context method so **if there aren't *.spec.js files that import the code you want to cover or  that piece of code (e.g. a component) is not imported in your application somewhere, you will not see it in the coverage output.**

**Comment by Foxandxss** [comment]
I think that doesn't happen in the ng2 version

**Comment by phra** [comment]
@Foxandxss do you think #49 is an acceptable solution for this? can i also proceed to merge #48 ?

**Comment by phra** [comment]
@Foxandxss i've found a generic way to include all the js files. i've updated the PR, let me know if we can merge #49 to close this issue.
