### ISSUE TITLE
Problem importing lodash partials from vendor.ts

### ISSUE THREAD

**Issue by phiphou** [preboot/angular-webpack#88]
Hi,

I'm using your seed to learn Webpack, and until now, everything works fine.

looking into the vendors.ts file, I see this is where you advice us to put vendor libs.

So I first tried with Lodash : in vendors.ts, I added `import 'lodash';` and in the app, when I need it, I just `set declare let _;` to avoid ts errors. Works fine. And works as it would, I mean, Lodash is included in the vendor generated bundle.

As second attempt, I tried to import only one Lodash method, like `Capitalize`for instance. 
Hard to explain here all the things I tried, but none of them worked.

Can you please tell me : 
- how I can do that
- is my goal (specific Lodash method included in vendor bundle and not in the app bundle) "the way it has to be"

Sorry for my bad english, I'm french, hope you'll understand me well ;)

**Comment by phiphou** [comment]
I finally make it working, like this : 

in vendor.ts , import 'lodash/capitalize';

and in app.ts, 

let capitalize = require('lodash/capitalize');
console.log(capitalize('bob'));

That works (lodash capitalize method is removed form app bundle and still in vendor bundle) , but the app.ts part seems ugly. Any idea ?

**Comment by Foxandxss** [comment]
Principal problem in here is to deal with typings. The `app` way is because you don't have typings (that is why you declared the `_` variable on the vendor file.

Isn't it any typings for lodash? Would be really weird.

**Comment by phiphou** [comment]
Thanks for the fast answer ;) 
I installed Lodash typings (yes, they exists!), but still no luck making it work... Maybe you should have a try and let me know what you did ?

**Comment by Foxandxss** [comment]
Will leave this open and try when I have a moment.

**Comment by phiphou** [comment]
Thanks, I'll continue investigating myself too ;)

**Comment by Menencia** [comment]
I've installed `lodash` and `@types/lodash` via NPM, added `import 'lodash'` in `vendor.ts` and `import * as _ from 'lodash'` in the component I want to use it, but in the component, my IDE (webstorm) shows me an error saying `lodash` has not been found :/

~~But my app is running without any errors (meaning lodash is found).

Is there a way to remove the IDE error?

**Comment by filipesilva** [comment]
@Menencia if it builds ok but you get the IDE errors, that is likely because your IDE is not using Typescript 2.0 yet. 

Using `@types` requires TS2.0 support, so you might have to configure your IDE to use your local typescript version. See https://www.jetbrains.com/help/webstorm/2016.2/transpiling-typescript-to-javascript.html#d240405e456 for webstorm.

**Comment by Menencia** [comment]
Thanks ! Actually, this post helped me with Sublime Text : https://github.com/Microsoft/TypeScript-Sublime-Plugin/issues/537#issuecomment-253490033
