### ISSUE TITLE
Images not loading from css

### ISSUE THREAD

**Issue by Foxandxss** [preboot/angular-webpack#9]
Perhaps based on the new Copy plugin? or webpack 2?

**Comment by THuRStoN** [comment]
It's working for me I've modified your script quite a bit but essentially I'm doing this for it to work.
I reference my images as:

**scss**
```
.logo {
  background-image: url('/assets/images/logo-iberdrola.png');
}
```
My make script does this: 

**webpack.make.js**
```
      // Copy assets from the public folder
      // Reference: https://github.com/kevlened/copy-webpack-plugin

      new CopyWebpackPlugin( [ {
        from: config.output.assets_src,
        to: config.output.assets_dst
      } ] )

      // Assets directories are defined as
      assets_src: `${ __dirname }/src/assets/images`,
      assets_dst: `${ __dirname }/assets/images`,
```

**Comment by Foxandxss** [comment]
I figured this out but never updated the issue.

the `css-loader` (not sure about scss to be honest) does a `require()` with the images, so the path needs to be relative to the css file.

I am going to make some changes and remove the need of CopyWebpackPlugin (hopefully) with the html-loader so css and html images will have the same behavior.

**Comment by THuRStoN** [comment]
OK! cool!
