### ISSUE TITLE
huge output files

### ISSUE THREAD

**Issue by ivancduran** [preboot/angular-webpack#90]
I'm not sure if it's a problem or just some misconfiguration.
but the output files vendor are approximately 4 to 5 mb and the polyfills more than 1mb

attached a pic

![img](https://cloud.githubusercontent.com/assets/1697846/15135968/5e2ced24-1642-11e6-8300-8242b87bf175.png)

thanks

**Comment by Foxandxss** [comment]
Sadly, it is neither.

Angular 2 is known for having a very big size. The core itself is like 4mb, almost 5 with router and http and 6+ with complete rxjs.

On prod vendor is about 1mb and polyfills like 100k. Still big.

Don't worry tho, when the offline compiler comes, we will be able to cut that size like a lot and when webpack reaches version 2 in a more stable way, I will update and implement tree shaking so every non used code will go away too.

**Comment by kuncevic** [comment]
That is the js output I am getting running `npm run build`

![image](https://cloud.githubusercontent.com/assets/1283734/15148560/16d2cb16-1709-11e6-8464-8ea718236947.png)

**Comment by ivancduran** [comment]
Thanks for the quick reply,
I test with npm build and the files are more smaller.
But definitely 1.3mb for a vendor.js file still's a big file.

I hope in the future this problem can be optimized.

**Comment by kuncevic** [comment]
In case you some one is not aware there is an interesting discussion on bundling/systemjs/commonjs on this issue https://github.com/angular/angular/issues/4278. 

Also I am just wondering in case of using a new router lazy loading feature sound like there is no js bundle needed at least in that format that it is happening right now. Sounds like in such case we would need multiple small bundles for each route. Any ideas how webpack is gonna play in case of router lazy loading?

**Comment by Foxandxss** [comment]
No idea, also no idea what will happen when the offline compiler comes.

Wild time for tooling sirs.

**Comment by tojocky** [comment]
Asset       Size  Chunks             Chunk Names
    css/app.ce1f64a45c4cb4691a03.css.map  109 bytes       1  [emitted]  app
       js/vendor.ce1f64a45c4cb4691a03.js    1.03 MB       0  [emitted]  vendor
    js/polyfills.ce1f64a45c4cb4691a03.js     116 kB       2  [emitted]  polyfills
        css/app.ce1f64a45c4cb4691a03.css  128 bytes       1  [emitted]  app
   js/vendor.ce1f64a45c4cb4691a03.js.map    6.72 MB       0  [emitted]  vendor
      js/app.ce1f64a45c4cb4691a03.js.map     604 kB       1  [emitted]  app
          js/app.ce1f64a45c4cb4691a03.js    98.5 kB       1  [emitted]  app
js/polyfills.ce1f64a45c4cb4691a03.js.map     886 kB       2  [emitted]  polyfills
                              index.html  569 bytes          [emitted]
                         img/favicon.ico    5.43 kB          [emitted]
                         img/angular.png    4.51 kB          [emitted]
                       service-worker.js   43 bytes          [emitted]

**Comment by Foxandxss** [comment]
Well, there is not much I can do if this is still an issue (apart from adding AoT support soon).
